import matplotlib.pyplot as plt

# LCG parameters
#m = 27
#a = 17
#c = 43
#X0 = 10  # Initial seed

# LCG parameters
m = 2**32
a = 1664525
c = 1013904223
X0 = 123456789  # Initial seed

# Function to generate random numbers using LCG
def lcg(m, a, c, X0, n):
    random_numbers = []
    X = X0
    for _ in range(n):
        X = (a * X + c) % m
        random_numbers.append(X)
    return random_numbers

# Generate 1000 random numbers
n = 1000
random_numbers = lcg(m, a, c, X0, n)

# Print the first 20 numbers to check the sequence
print("First 20 random numbers generated by LCG:")
for i in range(20):
    print(f"{i+1}: {random_numbers[i]}")


# Plotting the histogram
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
plt.hist(random_numbers, bins=20, color='skyblue', edgecolor='black')
plt.title('Histogram of LCG Random Numbers')
plt.xlabel('Random Number')
plt.ylabel('Frequency')

# Plotting the scatter plot of the random numbers
# For the scatter plot, we'll plot each number against its index to visualize the distribution over the sequence
plt.subplot(1, 2, 2)
plt.scatter(range(n), random_numbers, color='red')
plt.title('Scatter Plot of LCG Random Numbers')
plt.xlabel('Index')
plt.ylabel('Random Number')

plt.tight_layout()
plt.show()
